version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootvfkFYBNuuEuuiTy
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_usr
      MYSQL_PASSWORD: VYfyvfkFYBNuuEuuiTy
    volumes:
      - mysql:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_usr
      WORDPRESS_DB_PASSWORD: VYfyvfkFYBNuuEuuiTy
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      ["./:/var/www/html"]
volumes:
  mysql: {}
  
