name: Deploy Workflow

on:
  workflow_run:
    workflows: ["Build Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH and Run docker node image
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.TEST_SERVER_IP }}
        username: root
        password: ${{ secrets.TEST_PASSWORD }}
        port: 22
        script: |
          docker container stop node
          docker container rm node
          docker image rm antuvarghese/node
          docker pull antuvarghese/node:latest
          docker run --name node -p 80:8080 -d antuvarghese/node
          
