name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.1
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy to Linux Server
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.DEPLOY_SSH_KEY }} root@${{ secrets.TEST_SERVER_IP }} "docker pull antuvarghese/node:latest && docker run --name node -p 80:8080 -d antuvarghese/node"
